Update mmbuild

diff --git a/mmbuild b/mmbuild
--- a/mmbuild
+++ b/mmbuild
@@ -218,19 +218,74 @@ _clean() {
     exit 1
 }
 
+___validate_hostname(){
+    # test if new name conform the hostname requirements:
+    # test if var have only a-z 0-9 - and 63 char max and not begin or end with - and not have repeated -
+    
+    # https://www.freedesktop.org/software/systemd/man/org.freedesktop.hostname1.html
+        # Here are some recommendations to follow when generating a static (internet) hostname from a pretty name:
+        # Generate a single DNS label only, not an FQDN. That means no dots allowed. Strip them, or replace them by "-".
+        # It's probably safer not to use any non-ASCII chars, even if DNS allows this in some way these days. In fact, restrict your charset to a-zA-Z0-9, -.
+        # Try to avoid creating repeated "-", as well as "-" as the first or last char.
+        # Limit the hostname to 63 chars, which is the length of a DNS label
+        # Uppercase charaacters should be replaced with their lowercase equivalents.
+        
+    # man 5 hostname
+        # The /etc/hostname file configures the name of the local system that is set during boot using the sethostname(2) system call. It should contain a single newline-terminated hostname string. Comments (lines starting with a `#') are ignored. The hostname may be a free-form string up to 64 characters in length; however, it is recommended that it consists only of 7-bit ASCII lower-case characters and no spaces or dots, and limits itself to the format allowed for DNS domain name labels, even though this is not a strict requirement.
 
-if [ $# -lt 5 ]
+    # https://www.freedesktop.org/software/systemd/man/hostname.html
+        # /etc/hostname
+        # The file should contain a single newline-terminated hostname string. Comments (lines starting with a "#") are ignored. The hostname should be composed of up to 64 7-bit ASCII lower-case alphanumeric characters or hyphens forming a valid DNS domain name. It is recommended that this name contains only a single label, i.e. without any dots. Invalid characters will be filtered out in an attempt to make the name valid, but obviously it is recommended to use a valid name and not rely on this filtering.
+        
+    [[ "$1" =~ ^- ]] && { WARNC ; echo 'name should not begin with -' ; ENDC ; exit ; }
+    
+    [[ "$1" =~ -$ ]] && { WARNC ; echo 'name should not end with -' ; ENDC ; exit ; }
+
+    # --+ match succesive -
+    [[ "$1" =~ --+ ]] && { WARNC ; echo 'name should not contain succesive repeated -' ; ENDC ; exit ; }
+    
+    [[ ${#1} -gt 63 ]] && { WARNC ; echo 'name should not contain more than 63 char' ; ENDC ; exit ; }
+    
+    [[ "$1" =~ ^[a-z0-9-]+$ ]] || { WARNC ; echo 'name should contain only a-z (no uppercase) 0-9 or - chars' ; ENDC ; exit ; }
+    
+    # _____________
+    # i will never arrive to this because all this is done above, pero por si las moscas
+    # this will test if var have only a-z 0-9 - and 63 char max and not begin or end with -
+    # first [a-z0-9] is to test that hostname do not begin with -
+    # last [a-z0-9] is to test that hostname do not end with -
+    # [a-z0-9-]{1,61} match 1 to 61 of a-z 0-9 or -
+    [[ "$1" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]] || { WARNC ; echo 'name is invalid' ; ENDC ; exit ; }
+
+    
+    # tests : all this have to gave errors
+    # ___validate_hostname '-dash'
+    # ___validate_hostname 'dash-'
+    # ___validate_hostname 'dash--dash'
+    # ___validate_hostname 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz'  # 63char+z
+    # ___validate_hostname 'test.com'
+    # ___validate_hostname 'test_'
+}
+
+
+
+if [ $# -lt 4 ]
 then
-    WARNC ; echo "usage: $0 <image-file> <hostname> <OS name> <OSversion> [optional debootstrap args]" 1>&2 ; ENDC
+    WARNC ; echo "usage: $0 <image-file> <OS name> <OSversion> [optional debootstrap args]" 1>&2 ; ENDC
     # exit 1
 fi
 
+
 CTname=$1
-HOSTNAME=$2
-OSFLAVOUR=$3
-OSversion=$4
-ROOTPASSWD=$5
-shift 5
+OSFLAVOUR=$2
+OSversion=$3
+ROOTPASSWD=$4
+shift 4
+
+___validate_hostname "${CTname}"
+
+# validate too the CT clone name that I will use bellow
+CTname_clone=${CTname}-clean
+___validate_hostname "${CTname_clone}"
 
 
 # this will run always, EXIT es para cuando este script como script file, y RETURN es para cuando ejecuto la function directamente desde un shell
@@ -436,11 +491,11 @@ EOF
 ############################
 INFOC ; echo "configure hosts & hostname" ; ENDC
 
-echo $HOSTNAME > ${CTname_DIR}/etc/hostname
+echo ${CTname} > ${CTname_DIR}/etc/hostname
 
 cat <<EOF > ${CTname_DIR}/etc/hosts
 127.0.0.1       localhost
-127.0.1.1       $HOSTNAME
+127.0.1.1       ${CTname}
 # The following lines are desirable for IPv6 capable hosts
 ::1     localhost ip6-localhost ip6-loopback
 ff02::1 ip6-allnodes
@@ -829,7 +884,7 @@ echo "name:${CTname} ___ date:$(date)" >> ${CTname_DIR}/_MyMMfiles/_container_na
 ########################################################################################
 # best practice
 # best practice is to create a copy of this container before doing more changes , so i can clone this clean container whenever i want to do testing...etc
-cp -a ${CTname_DIR} ${CTname_DIR}-clean
+mm clone ${CTname} ${CTname_clone}
 # i do not need to register the clean version i can use mm to do it , it s better because it will create the service override ...Etc
 # ln -s ${CTname_DIR}-clean /var/lib/machines/${CTname}-clean
 
@@ -875,16 +930,16 @@ _help(){
     echo "
 ======================================================================================
 usage:
-mmbuild   imagename                Hostname (aZ09-)         OS       OS release   pass   [optional debootstrap args]
+mmbuild   imagename: Hostname (aZ09-)         OS       OS release   pass   [optional debootstrap args]
 
-mmbuild   buster${datenowForHostname}     buster${datenowForHostname}     debian   buster       bbbbbbnn
-mmbuild   bullseye${datenowForHostname}   bullseye${datenowForHostname}   debian   bullseye     bbbbbbnn
-mmbuild   testing${datenowForHostname}    testing${datenowForHostname}    debian   testing      bbbbbbnn
-mmbuild   unstable${datenowForHostname}   unstable${datenowForHostname}   debian   unstable     bbbbbbnn
+mmbuild   buster${datenowForHostname}     debian   buster       bbbbbbnn
+mmbuild   bullseye${datenowForHostname}   debian   bullseye     bbbbbbnn
+mmbuild   testing${datenowForHostname}    debian   testing      bbbbbbnn
+mmbuild   unstable${datenowForHostname}   debian   unstable     bbbbbbnn
 
-mmbuild   xenial${datenowForHostname}     xenial${datenowForHostname}     ubuntu   xenial       bbbbbbnn
-mmbuild   bionic${datenowForHostname}     bionic${datenowForHostname}     ubuntu   bionic       bbbbbbnn
-mmbuild   focal${datenowForHostname}      focal${datenowForHostname}      ubuntu   focal        bbbbbbnn
+mmbuild   xenial${datenowForHostname}     ubuntu   xenial       bbbbbbnn
+mmbuild   bionic${datenowForHostname}     ubuntu   bionic       bbbbbbnn
+mmbuild   focal${datenowForHostname}      ubuntu   focal        bbbbbbnn
 
 "
 }
